package com.example.solutionx.model

enum class ExtraComputation {
    HEALTH_RECOMMENDATIONS,
    DOMINANT_POLLUTANT_CONCENTRATION,
    POLLUTANT_CONCENTRATION,
    LOCAL_AQI,
    POLLUTANT_ADDITIONAL_INFO
}
